### PR TITLE
Add readme

### PR DESCRIPTION
**Pull request by trescube**
README.md had been missing so I wrote one up

### CODE REVIEW

**Comment by orangejulius** [comment]
Can you throw the header up there that we put on other projects? A good example is at https://github.com/pelias/openstreetmap/blob/master/README.md

And definitely include the travis badge, the image URL for this repo would be https://travis-ci.org/pelias/text-analyzer.svg

**Comment by orangejulius** [comment]
Beautiful. :shipit:

**Comment by dianashk** [comment]
:shipit:

**Comment by dianashk** [comment]
LGTM

**Pull request merged**
