### PR TITLE
Depend on a released addressit version

### PR DESCRIPTION
**Pull request by heikkipora**
Pull request from dianashk/addressit.git#temp has already been merged into addressit-1.3.1, use it instead of a git:// link

### CODE REVIEW

**Comment by heikkipora** [comment]
This commit https://github.com/DamonOehlman/addressit/commit/d1e2eae9d13166a2da4176af8e413f635ca3e29b fixed a bug that prevented multiword state names from being parsed properly. I suspect the failing test case (which uses "main particle new york" as test string and expects it to be non-parseable) is affected by this.

**Comment by trescube** [comment]
Unfortunately we have to stick with a specific addressit version for now due to it stripping leading 0's from postal codes in official npm versions.  We're in the process of deprecating addressit for the /search endpoint in favor of [libpostal](https://github.com/openvenues/libpostal) so hopefully this won't be much of an issue for very long.

**Comment by heikkipora** [comment]
I see, didn't think of that. The root problem I wanted to mitigate were the non-NPM registry dependencies you have - namely addressit and node-postal. I'd really really like to get pelias working in a special offline dev environment where dependencies are available only through an NPM registry mirror.  The node-postal project is not published in NPM registry at all so I also sent them a request for doing so :)

**Comment by orangejulius** [comment]
@trescube do we have a test for that leading zeros issue? Seems like something that could easily regress. (I had completely forgotten about it and was ready to :+1: this PR after the test was fixed)

**Comment by trescube** [comment]
libpostal is the wave of the future so it's probably a good thing to get nodepostal into npmjs.  We're keeping addressit around for the autocomplete endpoint for the time being but once we dig ourselves out from the libpostal refactoring, we'll run some tests to see if the special tagged version is still required.

**Comment by trescube** [comment]
@orangejulius I'm not sure about tests for that.

**Comment by orangejulius** [comment]
@trescube not only do we have said [test](https://github.com/pelias/text-analyzer/blob/master/test/addressItParser.js#L94), but the PR that @dianashk put in to fix the leading zero issue was merged (and mentioned by @heikkipora). So this PR LGTM and it is nice to be back on an NPM version of this package :)

**Comment by heikkipora** [comment]
Yes, see https://github.com/DamonOehlman/addressit/commit/9da3f04128c22b28710a993a4cedd0ad4f5aa4a3  :)

**Comment by dianashk** [comment]
LGTM _that npm version switch is_ 💵

**Comment by trescube** [comment]
Ah, well then, merge away!

**Comment by heikkipora** [comment]
Awesome! I'd appreciate if you'd +1 this one https://github.com/openvenues/node-postal/issues/5 for getting node-postal properly available as well.

**Pull request merged**
